//list of cities
export let Cities: string[] = [
  "New York City",
  "Tabriz",
  "Amritsar",
  "Beijing",
  "Perm",
  "Harbin",
  "Mexicali",
  "Columbus",
  "Timbuktu",
  "Raleigh",
  "Glasgow",
  "Horta (Azores)",
  "Dallas",
  "Virginia Beach",
  "Aberdeen",
  "Pelotas",
  "Whitehorse",
  "Koulikoro",
  "Hamilton",
  "Manama",
  "Aarhus",
  "Lviv",
  "Durango",
  "Mersin",
  "Shillong",
  "Shigatse",
  "St. George's",
  "Kuala Lumpur",
  "Medina",
  "Johannesburg",
  "Wollongong",
  "Ulan Bator",
  "Yokohama",
  "Ipoh",
  "Denver",
  "Yakutsk",
  "Hanga Roa",
  "Malacca Town",
  "Mecca",
  "Bergen",
  "Charlotte Amalie",
  "Vilnius",
  "Kano",
  "Palembang",
  "Ciudad del Este",
  "Tel Aviv",
  "Taipei",
  "Da Nang",
  "Vilnius",
  "Boston",
  "San Juan",
  "Tirana",
  "Lviv",
  "Hanga Roa",
  "Thiès",
  "Roseau",
  "Tunis",
  "Shanghai",
  "Guadalajara",
  "Aberdeen",
  "St. John's",
  "Santiago",
  "Washington",
  "Yokohama",
  "Nukuʻalofa",
  "Thiès",
  "Cannes",
  "Amsterdam",
  "Baghdad",
  "Accra",
  "Salzburg",
  "Yerevan",
  "Lusaka",
  "Adelaide",
  "Montreal",
  "Caracas",
  "Colombo",
  "Dammam",
  "Pontianak",
  "Tripoli",
  "Mamoudzou",
  "Kunming",
  "Johannesburg",
  "Monterrey",
  "Nanjing",
  "Ambon",
  "Vladivostok",
  "Astana",
  "Canberra",
  "Copenhagen",
  "Monterrey",
  "Ljubljana",
  "Ankara",
  "Gothenburg",
  "Willemstad",
  "São Paulo",
  "Kigali",
  "Yogyakarta (city)",
  "Bamako",
  "St. Louis",
  "Francistown",
  "Ljubljana",
  "Caracas",
  "Hamburg",
  "Tegucigalpa",
  "Gaza",
  "Hyderabad",
  "Cairo",
  "Chittagong",
  "Tallinn",
  "Chiang Mai",
  "Minsk",
  "Kawasaki",
  "Charlottetown",
  "Rawalpindi",
  "Ipoh",
  "Bahía Blanca",
  "Palikir",
  "Serekunda",
  "Newcastle",
  "Port Elizabeth",
  "Libreville",
  "Mexicali",
  "Denpasar",
  "Fukuoka",
  "Da Nang",
  "Taipei",
  "Ibiza",
  "Quetzaltenango",
  "Taiyuan",
  "Puebla",
  "Monterrey",
  "Istanbul",
  "Taichung",
  "San Diego",
  "Simferopol",
  "Cuiabá",
  "Yangon",
  "Quito",
  "Beirut",
  "Newcastle",
  "Sukhumi",
  "Marrakech",
  "Brikama",
  "Chihuahua",
  "Brisbane",
  "Anchorage",
  "Gaza",
  "Los Angeles",
  "Brasília",
  "Sofia",
  "Nizhny Novgorod",
  "Mwanza",
  "Hamilton",
  "Leipzig",
  "New York City",
  "Aberdeen",
  "Ashgabat",
  "Paramaribo",
  "Bandar Seri Begawan",
  "Bratsk",
  "Wollongong",
  "Mandurah",
  "Pekanbaru",
  "La Paz",
  "Vienna",
  "Taipei",
  "Cali",
  "Puerto Williams",
  "Hagåtña",
  "Hanover",
  "Sacramento",
  "São Tomé",
  "Jayapura",
  "Denver",
  "Belfast",
  "Handan",
  "Mashhad",
  "Seville",
  "Tripoli",
  "Glasgow",
  "Bratsk",
  "Batticaloa",
  "Mumbai",
  "Quebec City",
  "Gangtok",
  "Pune",
  "Melbourne",
  "Hong Kong",
  "Tagbilaran",
  "St. John's",
  "Dalian",
  "Nukus",
  "Bandung",
  "Mendoza",
  "Córdoba",
  "Mogadishu",
  "Chittagong",
  "Chiang Mai",
  "Dodoma",
  "Phuket (city)",
  "Srinagar",
  "Valencia",
  "Durango",
  "Pristina",
  "Vienna",
  "Canberra",
  "Ndola",
  "Chongjin",
  "Phuket (city)",
  "Dresden",
  "Makati City",
  "The Valley",
  "Lima",
  "St. Louis",
  "Suez",
  "Luanda",
  "Nassau",
  "Assis",
  "Bloemfontein",
  "Yellowknife",
  "Nukus",
  "Lviv",
  "Port Louis",
  "Lisbon",
  "Samara",
  "Huế",
  "Port Louis",
  "Serekunda",
  "Mecca",
  "Tashkent",
  "Sucre",
  "Chongqing",
  "San Juan",
  "Harbin",
  "Kinshasa",
  "Bilbao",
  "Kota Kinabalu",
  "Nairobi",
  "Tampere",
  "Road Town",
  "Fortaleza",
  "Sri Jayawardenapura-Kotte",
  "Jayapura",
  "Iquitos",
  "Mersin",
  "Berlin",
  "Ambon",
  "Bern",
  "Tijuana",
  "Dalian",
  "Milwaukee",
  "Miami",
  "Mecca",
  "Basse-Terre",
  "Perth",
  "Taiyuan",
  "Harare",
  "Saint John",
  "Geneva",
  "Durban",
  "Rochester",
  "Belfast",
  "Beirut",
  "Lisbon",
  "Francistown",
  "Tashkent",
  "Valdivia",
  "Santo Domingo",
  "El Aaiún",
  "Lagos",
  "Cologne",
  "St. Louis",
  "Bangui",
  "Shenzhen",
  "Patna",
  "Nice",
  "Maputo",
  "Algiers",
  "Kigali",
  "Bilbao",
  "Innsbruck",
  "Cebu City",
  "Darwin",
  "Cardiff",
  "Mérida",
  "Managua",
  "Havana",
  "Jacksonville",
  "Porto Alegre",
  "Phoenix",
  "Porto Alegre",
  "Kathmandu",
  "Louisville",
  "Melekeok",
  "Suez",
  "Oklahoma City",
  "Ndola",
  "Simferopol",
  "Lusaka",
  "Chennai",
  "Athens",
  "Punta Arenas",
  "New Delhi",
  "Las Palmas de Gran Canaria",
  "Denver",
  "Kuching",
  "Conakry",
  "Albuquerque",
  "Enugu",
  "Portland",
  "Split (city)",
  "Dhaka",
  "Avarua",
  "Santiago",
  "Mendoza",
  "Arequipa",
  "The Valley",
  "Antofagasta",
  "Oslo",
  "Niamey",
  "Kobe",
  "Wonsan",
  "New York City",
  "Medan",
  "Casablanca",
  "Luanda",
  "San Francisco",
  "Tirana",
  "Johannesburg",
  "Agartala",
  "Ürümqi",
  "Saint John",
  "Shigatse",
  "Douglas",
  "Cannes",
  "Zagreb",
  "Pontianak",
  "St. George's",
  "Port-au-Prince",
  "Bangkok",
  "Chengdu",
  "Ahmedabad",
  "Kharkiv",
  "Cleveland",
  "Angra do Heroísmo",
  "Edinburgh",
  "Cebu City",
  "Bern",
  "Denpasar",
  "Palikir",
  "Wellington",
  "Maracaibo",
  "Kathmandu",
  "Port Said",
  "Belfast",
  "Budapest",
  "Hamburg",
  "Stockholm",
  "Saint-Denis",
  "Kabul",
  "Siem Reap",
  "Washington",
  "Banjul",
  "Funafuti",
  "San José",
  "Brazzaville",
  "Changchun",
  "Funafuti",
  "Surabaya",
  "Vitória",
  "Willemstad",
  "Seville",
  "Guangzhou",
  "Amsterdam",
  "Forked River",
  "Curitiba",
  "San Carlos de Bariloche",
  "Birmingham",
  "Taichung",
  "Iquitos",
  "Almaty",
  "Freetown",
  "Brasília",
  "Bergen",
  "Wuhan",
  "Vancouver",
  "Dammam",
  "Dili",
  "Detroit",
  "Tirana",
  "Arequipa",
  "Zamboanga City",
  "Birkirkara",
  "Mecca",
  "Monterrey",
  "Willemstad",
  "Indianapolis",
  "Lima",
  "Juneau",
  "Stockholm",
  "Wonsan",
  "Espoo",
  "Frankfurt",
  "Cannes",
  "Yaoundé",
  "Bissau",
  "Quebec City",
  "Townsville",
  "Melbourne",
  "Lobamba",
  "Rochester",
  "Belém",
  "Naypyidaw",
  "Cayenne",
  "Saipan",
  "Dakar",
  "Nassau",
  "Graz",
  "Novosibirsk",
  "Antofagasta",
  "Boa Vista",
  "Aarhus",
  "Saint-Denis",
  "El Paso",
  "Liverpool",
  "Ludhiana",
  "Ibadan",
  "Lhasa",
  "Recife",
  "Incheon",
  "Asmara",
  "Antananarivo",
  "Stepanakert",
  "Jinan",
  "Virginia Beach",
  "Düsseldorf",
  "Vaduz",
  "Athens",
  "Charlotte Amalie",
  "Lucknow",
  "Mumbai",
  "Porto Velho",
  "Casablanca",
  "Cusco",
  "Auckland",
  "Leeds",
  "Fortaleza",
  "Honiara",
  "Indianapolis",
  "Prague",
  "Cape Town",
  "Liverpool",
  "Ashgabat",
  "Sabha",
  "Labasa",
  "Chişinău",
  "Jinan",
  "Salzburg",
  "Mecca",
  "Baghdad",
  "Tel Aviv",
  "Hai Phong",
  "Gothenburg",
  "Bursa",
  "San Fernando",
  "Dallas",
  "Los Angeles",
  "Minsk",
  "Niamey",
  "Naples",
  "Chaguanas",
  "Patna",
  "Ouagadougou",
  "Blantyre",
  "Kinshasa",
  "Omdurman",
  "Jinan",
  "Samara",
  "Luxembourg (city)",
  "Sri Jayawardenapura-Kotte",
  "Adelaide",
  "Quezon City",
  "Malmö",
  "La Paz",
  "Bergen",
  "Manzini",
  "Valletta",
  "Hagåtña",
  "Baku",
  "San José",
  "Toronto",
  "Iqaluit",
  "Alor Star",
  "Yerevan",
  "Namangan",
  "Chişinău",
  "Cannes",
  "Lilongwe",
  "Rotterdam",
  "Chiang Mai",
  "Bratislava",
  "Sapporo",
  "Siem Reap",
  "Sapporo",
  "Recife",
  "Ibiza",
  "Forked River",
  "Serekunda",
  "Bursa",
  "Zamboanga City",
  "Cairns",
  "Lubumbashi",
  "Havana",
  "Sukhumi",
  "Reykjavík",
  "Brazzaville",
  "Sitka",
  "Omdurman",
  "Kaesong",
  "Kharkiv",
  "Tórshavn",
  "Djibouti (city)",
  "Portland",
  "George Town",
  "Taipei",
  "Jakarta",
  "Valletta",
  "Quito",
  "Lyon",
  "Koulikoro",
  "Majuro",
  "Huế",
  "Guadalajara",
  "Ibiza",
  "Harbin",
  "Glasgow",
  "Bern",
  "Livingstone",
  "Maputo",
  "City of San Marino",
  "Kansas City",
  "Bursa",
  "Paramaribo",
  "Jacksonville",
  "Darwin",
  "Philadelphia",
  "Osaka",
  "Yerevan",
  "Recife",
  "Agartala",
  "Mumbai",
  "Batticaloa",
  "Recife",
  "Suez",
  "Campo Grande",
  "Portland",
  "Split (city)",
  "Kathmandu",
  "Dubai",
  "St. George's",
  "Siem Reap",
  "Belfast",
  "Manchester",
  "Srinagar",
  "Seoul",
  "Tokyo",
  "Sarajevo",
  "Santa Cruz de Tenerife",
  "Kraków",
  "Gold Coast",
  "Port Elizabeth",
  "Iqaluit",
  "Kaliningrad",
  "Dresden",
  "Saint-Pierre",
  "Cayenne",
  "Tel Aviv",
  "Hamilton",
  "Phoenix",
  "Kingstown",
  "Yangon",
  "Davao City",
  "Zanzibar City",
  "Guayaquil",
  "Kansas City",
  "Timbuktu",
  "Novosibirsk",
  "Seoul",
  "Nanning",
  "South Tarawa",
  "Incheon",
  "Nantes",
  "Islamabad",
  "George Town",
  "Wonsan",
  "Honolulu",
  "Recife",
  "Tabriz",
  "Cleveland",
  "Greenwich",
  "Providence",
  "Canberra",
  "Denver",
  "Nukuʻalofa",
  "Campinas",
  "Tokyo",
  "Jerusalem",
  "Kunming",
  "Tampere",
  "Yokohama",
  "Ndola",
  "Rockhampton",
  "Bissau",
  "Ashgabat",
  "Hyderabad",
  "Buenos Aires",
  "Phoenix",
  "Louisville",
  "Gothenburg",
  "Pristina",
  "San Diego",
  "Antwerp",
  "Kharkiv",
  "Monterrey",
  "Douala",
  "Bucharest",
  "Palembang",
  "Monaco",
  "Tartu",
  "Campo Grande",
  "Rockhampton",
  "Darwin",
  "San Diego",
  "Belgrade",
  "Adak",
  "Gaborone",
  "Ilhéus",
  "Surabaya",
  "Castries",
  "Edinburgh",
  "Whitehorse",
  "Magadan",
  "Cayenne",
  "Albuquerque",
  "Dalian",
  "Campo Grande",
  "Assis",
  "Pittsburgh",
  "Bratislava",
  "Aberdeen",
  "Nanjing",
  "Graz",
  "Kraków",
  "Singapore",
  "Koror",
  "Nukulaelae",
  "Hai Phong",
  "Vatican City",
  "Boa Vista",
  "Makati City",
  "Enugu",
  "Yamoussoukro",
  "Iquique",
  "Gdańsk",
  "Belmopan",
  "Tamale",
  "Vitória",
  "Mogadishu",
  "Stepanakert",
  "Porto Velho",
  "Koulikoro",
  "Geneva",
  "Damascus",
  "Berlin",
  "Charlotte",
  "Tijuana",
  "Vatican City",
  "Nukuʻalofa",
  "London",
  "Bergen",
  "Campo Grande",
  "Labasa",
  "Nouakchott",
  "Minsk",
  "San Juan",
  "Milwaukee",
  "Shenzhen",
  "Mandurah",
  "Kolkata",
  "Zamboanga City",
  "Seoul",
  "Tunis",
  "Bucharest",
  "Bridgetown",
  "Ottawa",
  "Zamboanga City",
  "Port Hedland",
  "Vitória",
  "Atlanta",
  "Taichung",
  "Phuket (city)",
  "Bratsk",
  "Winnipeg",
  "Lisbon",
  "Split (city)",
  "Jinan",
  "Gold Coast",
  "Muscat",
  "Christchurch",
  "Bangui",
  "Lisbon",
  "Pretoria",
  "Austin",
  "Saint Petersburg",
  "Jacksonville",
  "Munich",
  "Pristina",
  "Kota Kinabalu",
  "Harbin",
  "Hai Phong",
  "Linz",
  "Ibiza",
  "Aarhus",
  "Addis Ababa",
  "Yokohama",
  "Geneva",
  "Cairo",
  "Charlottetown",
  "Gdańsk",
  "Anchorage",
  "Ibadan",
  "Denver",
  "Jaipur",
  "London",
  "Juneau",
  "Chihuahua",
  "Dodoma",
  "Douglas",
  "Iquitos",
  "Yaren District",
  "Port Blair",
  "Zanzibar City",
  "Chihuahua",
  "Salt Lake City",
  "Wonsan",
  "Iqaluit",
  "Padang",
  "Macau",
  "Cape Town",
  "Lobamba",
  "Vienna",
  "St. Louis",
  "Enugu",
  "Lhasa",
  "Zürich",
  "Antofagasta",
  "Ludhiana",
  "Koulikoro",
  "Rio de Janeiro",
  "Makati City",
  "St. Louis",
  "Honiara",
  "Skopje",
  "Kaohsiung",
  "Kanpur",
  "Istanbul",
  "Prague",
  "Cork (city)",
  "Kuching",
  "Hilo",
  "Kansas City",
  "Peshawar",
  "Sofia",
  "Gibraltar",
  "Singapore",
  "Jakarta",
  "Pretoria",
  "Edinburgh",
  "Simferopol",
  "Ashgabat",
  "Anchorage",
  "Zamboanga City",
  "Guadalajara",
  "Shenzhen",
  "Kandy",
  "Anchorage",
  "Santo Domingo",
  "Norilsk",
  "Valletta",
  "Cork (city)",
  "Maracaibo",
  "Dodoma",
  "Newcastle",
  "Cayenne",
  "Málaga",
  "Paramaribo",
  "Labasa",
  "Baku",
  "Kabul",
  "Bissau",
  "Berlin",
  "Majuro",
  "Konya",
  "Denpasar",
  "Hagåtña",
  "Havana",
  "Kano",
  "Manaus",
  "London",
  "Ponta Delgada",
  "Palma",
  "Serekunda",
  "Shillong",
  "Rabat",
  "Denpasar",
  "Phnom Penh",
  "Guayaquil",
  "Oklahoma City",
  "Barcelona",
  "Milan",
  "Novosibirsk",
  "Sapporo",
  "Zagreb",
  "Basse-Terre",
  "City of San Marino",
  "Ibadan",
  "Kathmandu",
  "Barranquilla",
  "Curitiba",
  "Charlotte Amalie",
  "Tampa",
  "Odessa",
  "Kunming",
  "Kharkiv",
  "Thimphu",
  "Banjul",
  "Bissau",
  "Arbil",
  "Jayapura",
  "Munich",
  "Shillong",
  "Kyoto",
  "Chaguanas",
  "Monaco",
  "Surabaya",
  "Seville",
  "Kota Bharu",
  "Da Nang",
  "Porto Alegre",
  "Invercargill",
  "Suva",
  "Lusaka",
  "Iquitos",
  "Bahía Blanca",
  "Kabul",
  "Stepanakert",
  "Greenwich",
  "Jersey City",
  "Phnom Penh",
  "Hiroshima",
  "Edmonton",
  "Busan",
  "La Serena",
  "Porto-Novo",
  "Canberra",
  "Hobart",
  "São Tomé",
  "Edmonton",
  "Assis",
  "St. Louis",
  "Yekaterinburg",
  "Kingstown",
  "Fukuoka",
  "Houston",
  "Pago Pago",
  "Nukuʻalofa",
  "Baltimore",
  "Rotterdam",
  "Vienna",
  "Mashhad",
  "Bangalore",
  "Hobart",
  "Iquitos",
  "St. Louis",
  "Winnipeg",
  "Naples",
  "Zagreb",
  "Xi'an",
  "Adak",
  "Los Angeles",
  "Tabriz",
  "Recife",
  "Srinagar",
  "Qingdao",
  "Santa Cruz de Tenerife",
  "Bogotá",
  "Veracruz",
  "Moroni",
  "Edinburgh",
  "Port Louis",
  "Santa Cruz de la Sierra",
  "Stockholm",
  "Espoo",
  "Hai Phong",
  "Perm",
  "St. Louis",
  "Kiev",
  "Santa Cruz de Tenerife",
  "Zagreb",
  "Gangtok",
  "Luxembourg (city)",
  "Semarang",
  "Hamilton",
  "Chihuahua",
  "Dodoma",
  "Porto Velho",
  "Palma",
  "Ljubljana",
  "Johor Bahru",
  "Enugu",
  "Miami",
  "London",
  "Montreal",
  "Aarhus",
  "Lubumbashi",
  "Yakutsk",
  "Vientiane",
  "Koulikoro",
  "Medina",
  "Medina",
  "Agartala",
  "Leipzig",
  "Manzini",
  "Asmara",
  "Nukus",
  "Roseau",
  "Santiago",
  "Chongqing",
  "Maseru",
  "Kathmandu",
  "Wellington",
  "N'Djamena",
  "Casablanca",
  "Xi'an",
  "Bridgetown",
  "Malabo",
  "Guangzhou",
  "Pristina",
  "Cleveland",
  "Casablanca",
  "Bern",
  "Stanley",
  "New Delhi",
  "Hiroshima",
  "Odessa",
  "Pyongyang",
  "Phoenix",
  "Dodoma",
  "Dresden",
  "Suva",
  "Davao City",
  "Alexandria",
  "Nakhon Ratchasima",
  "Tel Aviv",
  "Albuquerque",
  "Rockhampton",
  "Mashhad",
  "Cleveland",
  "Dunedin",
  "La Serena",
  "Nukulaelae",
  "Houston",
  "Willemstad",
  "Leipzig",
  "Enugu",
  "Cologne",
  "Fredericton",
  "Mamoudzou",
  "Montreal",
  "Melbourne",
  "Detroit",
  "Memphis",
  "Sana'a",
  "Puebla",
  "St. George's",
  "São José dos Campos",
  "Athens",
  "Hiroshima",
  "Malé",
  "Hilo",
  "Dammam",
  "Papeete",
  "San Fernando",
  "Conakry",
  "Lobamba",
  "Nakhon Ratchasima",
  "Banda Aceh",
  "Gibraltar",
  "Houston",
  "Pontianak",
  "Semarang",
  "Shigatse",
  "Kolkata",
  "Madrid",
  "Durban",
  "Banjul",
  "Perth",
  "Toronto",
  "Dunedin",
  "Nantes",
  "Yaren District",
  "Nassau",
  "Buffalo",
  "Rochester",
  "Melbourne",
  "Stepanakert",
  "Blantyre",
  "Santo Domingo",
  "Moscow",
  "Dallas",
  "Lubumbashi",
  "Sucre",
  "Kathmandu",
  "Ho Chi Minh City",
  "Norilsk",
  "Balikpapan",
  "Pekanbaru",
  "Aarhus",
  "Durango",
  "Omsk",
  "Porto",
  "Hanoi",
  "Banjul",
  "Belmopan",
  "Charlotte Amalie",
  "Mata-Utu",
  "Kota Kinabalu",
  "Saint-Denis",
  "Vancouver",
  "Basra",
  "Salzburg",
  "Kuching",
  "Denpasar",
  "Niamey",
  "Denpasar",
  "Nakhon Ratchasima",
  "Beijing",
  "Chennai",
  "Basse-Terre",
  "St. George's",
  "Kuala Lumpur",
  "Kingston",
  "Memphis",
  "Wollongong",
  "Córdoba",
  "Detroit",
  "Tskhinvali",
  "Chengdu",
  "Tallinn",
  "Peshawar",
  "Bratsk",
  "Siem Reap",
  "Suez",
  "Bridgetown",
  "Hagåtña",
  "Zürich",
  "Phnom Penh",
  "Koror",
  "Medan",
  "Vitória",
  "Tirana",
  "Multan",
  "Omdurman",
  "Honiara",
  "Freetown",
  "Libreville",
  "Greenwich",
  "Santiago",
  "Weno",
  "Forked River",
  "Palikir",
  "Luxor",
  "Glasgow",
  "Oklahoma City",
  "Mexicali",
  "Kano",
  "Philadelphia",
  "Phuket (city)",
  "Leeds",
  "Petropavlovsk-Kamchatsky",
  "Chişinău",
  "Antwerp",
  "Luxor",
  "Bujumbura",
  "Mérida",
  "Ottawa",
  "Fairbanks",
  "Bloemfontein",
  "Brazzaville",
  "Djibouti (city)",
  "Edinburgh",
  "Dalian",
  "Honiara",
  "Bangkok",
  "Stockholm",
  "Luanda",
  "Rome",
  "Pune",
  "Pune",
  "Konya",
  "Bandung",
  "Surabaya",
  "Valparaíso",
  "Mexicali",
  "Medellín",
  "Lucknow",
  "Innsbruck",
  "Zapopan",
  "Koror",
  "Ottawa",
  "Macapá",
  "Tallinn",
  "Almaty",
  "New Delhi",
  "Barranquilla",
  "Louisville",
  "Kolkata",
  "Sofia",
  "Harbin",
  "Bishkek",
  "Pristina",
  "Road Town",
  "Concepción",
  "Malé",
  "Papeete",
  "Dili",
  "Malabo",
  "Chicago",
  "Port Elizabeth",
  "La Paz",
  "Balikpapan",
  "Sofia",
  "Surabaya",
  "Bandung",
  "Malang",
  "Adak",
  "Fredericton",
  "Amritsar",
  "Aarhus",
  "Curitiba",
  "Nashville",
  "Suva",
  "Xining",
  "Yekaterinburg",
  "Santo Domingo",
  "Berlin",
  "Moscow",
  "Phnom Penh",
  "Havana",
  "Xi'an",
  "Kandy",
  "Simferopol",
  "Bulawayo",
  "Sitka",
  "Mogadishu",
  "Nakhon Ratchasima",
  "Arbil",
  "San José",
  "Kingstown",
  "Mashhad",
  "Taichung",
  "Ibadan",
  "Multan",
  "Chihuahua",
  "Faisalabad",
  "Yokohama",
  "Lisbon",
  "Zapopan",
  "Chennai",
  "El Paso",
  "Marrakech",
  "Udon Thani",
  "Stockholm",
  "Saipan",
  "Sana'a",
  "Tallinn",
  "Pretoria",
  "Salt Lake City",
  "Indianapolis",
  "Bangalore",
  "Qingdao",
  "Los Angeles",
  "Chicago",
  "Belgrade",
  "São José dos Campos",
  "Ottawa",
  "Thimphu",
  "Libreville",
  "Guadalajara",
  "Honolulu",
  "Córdoba",
  "Qingdao",
  "Ushuaia",
  "Surabaya",
  "Pretoria",
  "Fairbanks",
  "Iquitos",
  "Banda Aceh",
  "Tokyo",
  "Yangon",
  "Padang",
  "Shigatse",
  "Oslo",
  "Dar es Salaam",
  "Port-au-Prince",
  "Charlotte",
  "Shenzhen",
  "South Tarawa",
  "St. John's",
  "Kingston",
  "Perm",
  "Ho Chi Minh City",
  "Anchorage",
  "Port Hedland",
  "Yangon",
  "Regina",
  "Koulikoro",
  "Zhengzhou",
  "The Valley",
  "Qingdao",
  "Vitória",
  "Hamilton",
  "Perth",
  "Nassau",
  "Auckland",
  "Perth",
  "Almaty",
  "Pittsburgh",
  "Milwaukee",
  "Luanda",
  "Porto Velho",
  "Charlottetown",
  "Winnipeg",
  "Kandahar",
  "Jersey City",
  "Mamoudzou",
  "Fairbanks",
  "Bloemfontein",
  "Cannes",
  "Tokyo",
  "Banjul",
  "San José",
  "Montevideo",
  "Apia",
  "Kanpur",
  "Edinburgh",
  "Jakarta",
  "Muscat",
  "Santa Cruz de la Sierra",
  "Guadalajara",
  "Canberra",
  "São Paulo",
  "Accra",
  "Belém",
  "Amsterdam",
  "Santiago de Cuba",
  "Chicago",
  "Wuhan",
  "Cuiabá",
  "Makassar",
  "Manaus",
  "Lubumbashi",
  "Saint-Denis",
  "Zapopan",
  "Ilhéus",
  "Las Palmas de Gran Canaria",
  "El Aaiún",
  "Yellowknife",
  "Tampere",
  "Cartagena",
  "Sukhumi",
  "Cincinnati",
  "Multan",
  "Antwerp",
  "Blantyre",
  "Singapore",
  "Padang",
  "Invercargill",
  "San Salvador",
  "Hargeisa",
  "Yamoussoukro",
  "Rome",
  "Valparaíso",
  "Brazzaville",
  "Brazzaville",
  "Asmara",
  "Lima",
  "Nuuk",
  "Nagoya",
  "Riverside",
  "İzmir",
  "Changchun",
  "Málaga",
  "Kaesong",
  "Sapporo",
  "Nairobi",
  "City of San Marino",
  "Cartagena",
  "Quito",
  "Macau",
  "Edmonton",
  "Albuquerque",
  "Suez",
  "Mérida",
  "Hat Yai",
  "Medellín",
  "Nantes",
  "Petropavlovsk-Kamchatsky",
  "Dresden",
  "Luxor",
  "Invercargill",
  "Toulouse",
  "Denpasar",
  "Mashhad",
  "Omdurman",
  "Abidjan",
  "Cairns",
  "Yekaterinburg",
  "Bishkek",
  "Kolkata",
  "Bandung",
  "Kuching",
  "Kunming",
  "Avarua",
  "Changchun",
  "Francistown",
  "The Valley",
  "Tripoli",
  "Albuquerque",
  "Ludhiana",
  "Dubai",
  "Newcastle",
  "Ambon",
  "Dallas",
  "Melbourne",
  "Hagåtña",
  "Maputo",
  "Melekeok",
  "Madrid",
  "Vladivostok",
  "Tskhinvali",
  "Lucknow",
  "Algiers",
  "Zamboanga City",
  "Kiev",
  "Ürümqi",
  "Belém",
  "Islamabad",
  "Valletta",
  "Nukulaelae",
  "Hyderabad",
  "Ambon",
  "Peshawar",
  "Yaren District",
  "Cape Town",
  "Boston",
  "Berlin",
  "Denpasar",
  "Almaty",
  "Ho Chi Minh City",
  "Salt Lake City",
  "Sarajevo",
  "New Delhi",
  "Wichita",
  "Bandar Seri Begawan",
  "Sri Jayawardenapura-Kotte",
  "Malabo",
  "Tehran",
  "Agartala",
  "Bissau",
  "Aberdeen",
  "Johannesburg",
  "Yaren District",
  "São Tomé",
  "Havana",
  "Ahmedabad",
  "Batticaloa",
  "Praia",
  "Abidjan",
  "Moroni",
  "Reykjavík",
  "Arbil",
  "Kigali",
  "Kingstown",
  "Bamako",
  "Norilsk",
  "Doha",
  "Nukuʻalofa",
  "Denver",
  "Santiago de Cuba",
  "Samara",
  "Montevideo",
  "Nagpur",
  "Luxor",
  "Rome",
  "Málaga",
  "Saint John",
  "Libreville",
  "Calama",
  "Alofi",
  "Podgorica",
  "Split (city)",
  "Surat Thani",
  "Banjul",
  "Dammam",
  "Pago Pago",
  "Iloilo City",
  "Miami",
  "Road Town",
  "São Tomé",
  "Dallas",
  "Mashhad",
  "Charlottetown",
  "Greenwich",
  "Bridgetown",
  "Charlotte Amalie",
  "Johor Bahru",
  "Nakhon Ratchasima",
  "Caracas",
  "Belize City",
  "Vientiane",
  "Lviv",
  "Hyderabad",
  "Padang",
  "Gothenburg",
  "Sofia",
  "Edinburgh",
  "Srinagar",
  "Horta (Azores)",
  "Xi'an",
  "Namangan",
  "Atlanta",
  "Santa Cruz de Tenerife",
  "Rockhampton",
  "Vladivostok",
  "Dallas",
  "Saskatoon",
  "Cape Town",
  "Gibraltar",
  "Okinawa",
  "Pyongyang",
  "Buenos Aires",
  "Harare",
  "Zhengzhou",
  "Barranquilla",
  "Bern",
  "Berlin",
  "Zürich",
  "Bogor",
  "Malmö",
  "Niamey",
  "Singapore",
  "Brisbane",
  "Roseau",
  "Nukus",
  "Majuro",
  "Surabaya",
  "São Tomé",
  "Cape Town",
  "Minsk",
  "Adelaide",
  "N'Djamena",
  "Atlanta",
  "Vatican City",
  "Fort-de-France",
  "Multan",
  "Libreville",
  "Nashville",
  "Fairbanks",
  "Faisalabad",
  "Belmopan",
  "Nizhny Novgorod",
  "Thiès",
  "Tórshavn",
  "Munich",
  "Sydney",
  "Buenos Aires",
  "Whitehorse",
  "Philadelphia",
  "Belgrade",
  "Providence",
  "Portland",
  "Ahmedabad",
  "Istanbul",
  "Rome",
  "Mogadishu",
  "Auckland",
  "Bandung",
  "Brazzaville",
  "Mwanza",
  "Santiago",
  "Providence",
  "Medan",
  "Douglas",
  "Douglas",
  "Changchun",
  "Albuquerque",
  "Buenos Aires",
  "New Delhi",
  "Hilo",
  "Livingstone",
  "Porto-Novo",
  "Ulan Bator",
  "Ljubljana",
  "Jamestown",
  "Amman",
  "Padang",
  "Bujumbura",
  "Tagbilaran",
  "Arbil",
  "Forked River",
  "Douala",
  "Porto Velho",
  "Dededo",
  "San José",
  "Durban",
  "Malabo",
  "Copenhagen",
  "Nukuʻalofa",
  "Mumbai",
  "Kabul",
  "Basra",
  "Papeete",
  "Lviv",
  "Vatican City",
  "Birkirkara",
  "Mérida",
  "Samara",
  "Athens",
  "Adana",
  "Managua",
  "Lubumbashi",
  "The Hague",
  "Buffalo",
  "San Juan",
  "Vancouver",
  "Prague",
  "Salt Lake City",
  "Amman",
  "Boa Vista",
  "Pelotas",
  "Chişinău",
  "Dodoma",
  "Simferopol",
  "Medina",
  "Riverside",
  "Cali",
  "Manchester",
  "Majuro",
  "Munich",
  "Espoo",
  "Kaesong",
  "Saint-Pierre",
  "Santa Cruz de Tenerife",
  "Chongqing",
  "Cockburn Town",
  "Oklahoma City",
  "Mecca",
  "Tabriz",
  "Dallas",
  "Francistown",
  "Port Blair",
  "Antwerp",
  "Winnipeg",
  "Sitka",
  "Mexicali",
  "Oranjestad",
  "Kanpur",
  "Barcelona",
  "Philadelphia",
  "Oslo",
  "Dodoma",
  "Adamstown",
  "St. George's",
  "Multan",
  "Washington",
  "Boston",
  "El Paso",
  "Bloemfontein",
  "Moroni",
  "Kandy",
  "Labasa",
  "St. George's",
  "Thessaloniki",
  "Tórshavn",
  "Bangui",
  "Cleveland",
  "Bursa",
  "Siem Reap",
  "Lisbon",
  "Malé",
  "Santa Cruz de la Sierra",
  "South Tarawa",
  "Wuhan",
  "Luanda",
  "Amsterdam",
  "Cali",
  "Almaty",
  "Porto Velho",
  "Wonsan",
  "Yellowknife",
  "Port Vila",
  "Baku",
  "Phuket (city)",
  "Kanpur",
  "Casablanca",
  "Pontianak",
  "Malacca Town",
  "Hangzhou",
  "Stepanakert",
  "Buffalo",
  "Surabaya",
  "Karachi",
  "Ciudad del Este",
  "Avarua",
  "Dar es Salaam",
  "Tegucigalpa",
  "Managua",
  "Regina",
  "Abidjan",
  "Lobamba",
  "Beirut",
  "Malmö",
  "Geelong",
  "Khartoum",
  "Kiev",
  "Changchun",
  "Tartu",
  "Tehran",
  "Rabat",
  "Algiers",
  "Brikama",
  "Punta Arenas",
  "Alor Star",
  "Saint-Pierre",
  "Medina",
  "The Valley",
  "Christchurch",
  "Guadalajara",
  "Zapopan",
  "Vancouver",
  "Incheon",
  "Darwin",
  "Sofia",
  "Omdurman",
  "Majuro",
  "Santa Cruz de la Sierra",
  "Vientiane",
  "Serekunda",
  "St. John's",
  "Surabaya",
  "Nouméa",
  "Dibrugarh",
  "Angra do Heroísmo",
  "Concepción",
  "St. Louis",
  "Cairo",
  "Bangui",
  "Wichita",
  "Nashville",
  "Mata-Utu",
  "Edinburgh",
  "Medan",
  "Cork (city)",
  "Singapore",
  "Hai Phong",
  "Astana",
  "Lilongwe",
  "Jeddah",
  "Rosario",
  "Incheon",
  "Malé",
  "Angra do Heroísmo",
  "Baltimore",
  "Tianjin",
  "Puebla",
  "Pekanbaru",
  "Makassar",
  "Mecca",
  "Papeete",
  "Warsaw",
  "Surabaya",
  "Malmö",
  "Mexico City",
  "Beijing",
  "Rosario",
  "Bucharest",
  "Washington",
  "Providence",
  "Asmara",
  "Nassau",
  "Tehran",
  "Port Said",
  "Paramaribo",
  "Santiago de Cuba",
  "Hamilton",
  "Pretoria",
  "Townsville",
  "Port Elizabeth",
  "Naples",
  "Copenhagen",
  "Vaduz",
  "Makati City",
  "Shenzhen",
  "Zamboanga City",
  "Kingston",
  "Cartagena",
  "Chişinău",
  "Taichung",
  "Iqaluit",
  "Regina",
  "Iqaluit",
  "Tijuana",
  "Chongjin",
  "Fredericton",
  "Dushanbe",
  "Brikama",
  "Bogor",
  "Edinburgh",
  "Jacksonville",
  "Surat",
  "Mersin",
  "Shenyang",
  "Malacca Town",
  "Valdivia",
  "Valencia",
  "Bishkek",
  "Sapporo",
  "São Paulo",
  "Cardiff",
  "Palma",
  "Dunedin",
  "Francistown",
  "Mendoza",
  "Málaga",
  "Bratislava",
  "Nuuk",
  "Conakry",
  "Podgorica",
  "Rawalpindi",
  "Samara",
  "Kuwait City",
  "Sydney",
  "Patna",
  "Cartagena",
  "Curitiba",
  "Bratislava",
  "Thiès",
  "Oranjestad",
  "Vitória",
  "Port Moresby",
  "Ashgabat",
  "Ottawa",
  "Guangzhou",
  "Greenwich",
  "Thiès",
  "Providence",
  "Namangan",
  "Sucre",
  "Roseau",
  "İzmir",
  "Khartoum",
  "Rio de Janeiro",
  "Bangui",
  "Johannesburg",
  "Qingdao",
  "Munich",
  "Bergen",
  "Gdańsk",
  "Moscow",
  "Longyearbyen",
  "Handan",
  "Papeete",
  "İzmir",
  "Sacramento",
  "Amritsar",
  "Patna",
  "Libreville",
  "Da Nang",
  "Recife",
  "Dushanbe",
  "Marrakech",
  "Ludhiana",
  "Muscat",
  "Simferopol",
  "Santiago",
  "Havana",
  "Longyearbyen",
  "Louisville",
  "Barranquilla",
  "Riverside",
  "Veracruz",
  "Cotonou",
  "Adamstown",
  "Nukus",
  "Labasa",
  "Osaka",
  "Maceió",
  "Mendoza",
  "Concepción",
  "Managua",
  "Naples",
  "Dalian",
  "Bridgetown",
  "Gangtok",
  "Edinburgh",
  "Leipzig",
  "Austin",
  "Rotterdam",
  "Veracruz",
  "Yakutsk",
  "Winnipeg",
  "Ottawa",
  "Amman",
  "Mata-Utu",
  "Rabat",
  "Port Hedland",
  "Dubai",
  "Luxor",
  "Perm",
  "Lisbon",
  "Faisalabad",
  "Ludhiana",
  "Makassar",
  "Belfast",
  "İzmir",
  "Toulouse",
  "George Town",
  "Mata-Utu",
  "El Paso",
  "Peshawar",
  "Pattaya",
  "St. George's",
  "Manila",
  "San Diego",
  "Louisville",
  "Kuala Lumpur",
  "Raleigh",
  "Bratsk",
  "Tirana",
  "Port Vila",
  "South Tarawa",
  "Rio Branco",
  "Albuquerque",
  "Nanning",
  "Townsville",
  "Andorra la Vella",
  "Vatican City",
  "Indianapolis",
  "Charlottetown",
  "Ljubljana",
  "Havana",
  "Port Elizabeth",
  "Dalian",
  "El Aaiún",
  "Tallinn",
  "Ibadan",
  "Serekunda",
  "Maceió",
  "Campo Grande",
  "Yogyakarta (city)",
  "El Aaiún",
  "Medan",
  "George Town",
  "Chicago",
  "Cape Town",
  "Warsaw",
  "Pune",
  "Bandar Seri Begawan",
  "Chişinău",
  "Fukuoka",
  "Kandy",
  "Kaesong",
  "Phuket (city)",
  "Alofi",
  "Dili",
  "Birkirkara",
  "Mogadishu",
  "Tskhinvali",
  "Tripoli",
  "Vaduz",
  "Bursa",
  "Nice",
  "Baku",
  "Toronto",
  "Cleveland",
  "İzmir",
  "Podgorica",
  "Antananarivo",
  "Srinagar",
  "Saint Petersburg",
  "Palikir",
  "Handan",
  "Iquitos",
  "Ciudad del Este",
  "Ndola",
  "Chicago",
  "Lahore",
  "Calama",
  "Shenyang",
  "Sapporo",
  "Nagoya",
  "Chiang Mai",
  "Pune",
  "Banjul",
  "Winnipeg",
  "Makassar",
  "Las Vegas",
  "Turin",
  "Kandahar",
  "Chaguanas",
  "Naples",
  "Agartala",
  "Boa Vista",
  "Amsterdam",
  "Barcelona",
  "Anadyr (town)",
  "Rome",
  "Qingdao",
  "St. Louis",
  "Hanga Roa",
  "Ljubljana",
  "Yaoundé",
  "Lomé",
  "Saint-Denis",
  "Sana'a",
  "Boston",
  "Turin",
  "Banda Aceh",
  "Bridgetown",
  "Kinshasa",
  "Athens",
  "Taiyuan",
  "Djibouti (city)",
  "Nanning",
  "Stanley",
  "Kaohsiung",
  "Alor Star",
  "Asunción",
  "Amman",
  "Tallinn",
  "Innsbruck",
  "Barranquilla",
  "Perm",
  "Malabo",
  "Alofi",
  "Beijing",
  "Santo Domingo",
  "The Valley",
  "Jacksonville",
  "Rabat",
  "Adelaide",
  "Geelong",
  "Kota Kinabalu",
  "Anadyr (town)",
  "El Paso",
  "Ciudad del Este",
  "Xi'an",
  "Punta Arenas",
  "San Fernando",
  "Cockburn Town",
  "El Paso",
  "Freetown",
  "Bern",
  "Nakhon Ratchasima",
  "Almaty",
  "Sitka",
  "Kigali",
  "Veracruz",
  "Luxor",
  "Dubai",
  "Aarhus",
  "Hyderabad",
  "Belmopan",
  "Kaohsiung",
  "Bergen",
  "Ho Chi Minh City",
  "Malabo",
  "Bissau",
  "Bamako",
  "Anadyr (town)",
  "Saint-Pierre",
  "Zhengzhou",
  "Belém",
  "Yogyakarta (city)",
  "San Diego",
  "Buffalo",
  "Harare",
  "Astana",
];
